###############################################################################
# Sloan Digital Sky Survey (SDSS)
# IDL support code for products: idlmapper, idlspec2d
#
# S. Burles & D. Schlegel
###############################################################################

SHELL = /bin/sh
#
all :;
#
# Install things in their proper places in $(IDLUTILS_DIR)
#
install :
	- cp *.h $(IDLUTILS_DIR)/include
	- cp Makefile $(IDLUTILS_DIR)/include

clean :
	- /bin/rm -f *~ core

