###############################################################################
# Sloan Digital Sky Survey (SDSS)
# IDL support code for products: idlmapper, idlspec2d
#
# S. Burles & D. Schlegel
###############################################################################

SHELL = /bin/sh
#
all :;

install :
	- cp idlutils.table $(IDLUTILS_DIR)/ups
	- cp Makefile $(IDLUTILS_DIR)/ups

clean :
	rm -f *~ core *.bak *.orig *.old .#* #*#
